<a href="https://colab.research.google.com/github/byiringiroscar/NLP-Data-science-ML-and-Artificial-Intelligence/blob/main/Predict_house_price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [2]:
# Load your dataset (replace with your file path or URL)
df = pd.read_csv('/content/Cleaned_data_for_model.csv')

In [3]:
df.head()

,Unnamed: 0,property_type,price,location,city,baths,purpose,bedrooms,Area_in_Marla
0,0,Flat,10000000,G-10,Islamabad,2,For Sale,2,4.0
1,1,Flat,6900000,E-11,Islamabad,3,For Sale,3,5.6
2,2,House,16500000,G-15,Islamabad,6,For Sale,5,8.0
3,3,House,43500000,Bani Gala,Islamabad,4,For Sale,4,40.0
4,4,House,7000000,DHA Defence,Islamabad,3,For Sale,3,8.0

In [6]:
# Drop the 'index' and 'Unnamed: 0' columns (they are redundant)
df = df.drop(['index', 'Unnamed: 0'], axis=1, errors='ignore')

In [7]:
df.head()

,property_type,price,location,city,baths,purpose,bedrooms,Area_in_Marla
0,Flat,10000000,G-10,Islamabad,2,For Sale,2,4.0
1,Flat,6900000,E-11,Islamabad,3,For Sale,3,5.6
2,House,16500000,G-15,Islamabad,6,For Sale,5,8.0
3,House,43500000,Bani Gala,Islamabad,4,For Sale,4,40.0
4,House,7000000,DHA Defence,Islamabad,3,For Sale,3,8.0

In [8]:
# Handle categorical features by one-hot encoding
df = pd.get_dummies(df, columns=['property_type', 'location', 'city', 'purpose'], drop_first=True)

In [11]:
# Separate features (X) and target (y)
X = df.drop('price', axis=1)  # Features
y = df['price']  # Target variable

In [15]:
y

0        10000000
1         6900000
2        16500000
3        43500000
4         7000000
           ...
99494     7500000
99495     8800000
99496    14000000
99497    14000000
99498     9000000
Name: price, Length: 99499, dtype: int64

In [16]:
# Normalize numerical features (baths, bedrooms, Area_in_Marla)
scaler = StandardScaler()
X[['baths', 'bedrooms', 'Area_in_Marla']] = scaler.fit_transform(X[['baths', 'bedrooms', 'Area_in_Marla']])

In [17]:
# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
# Print the shape of the data to check
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(79599, 1402) (19900, 1402) (79599,) (19900,)

In [19]:
# Step 7: Build the Neural Network Model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, input_dim=X_train.shape[1], activation='relu'),  # Hidden layer 1
    tf.keras.layers.Dense(32, activation='relu'),  # Hidden layer 2
    tf.keras.layers.Dense(1, activation='linear')  # Output layer (regression)
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
# Step 8: Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# Step 9: Train the model
history = model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test), batch_size=32)

# Step 10: Evaluate the model on the test set
loss, mae = model.evaluate(X_test, y_test)
print(f'Mean Absolute Error: {mae}')

# Step 11: Make predictions on the test set
y_pred = model.predict(X_test)

# Step 12: Calculate Mean Absolute Error using sklearn
from sklearn.metrics import mean_absolute_error
mae_value = mean_absolute_error(y_test, y_pred)
print(f'Mean Absolute Error (from sklearn): {mae_value}')

Epoch 1/100
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 203466542678016.0000 - mae: 9958386.0000 - val_loss: 176939314708480.0000 - val_mae: 9357374.0000
Epoch 2/100
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 161274260357120.0000 - mae: 8922520.0000 - val_loss: 121604608622592.0000 - val_mae: 7758215.0000
Epoch 3/100
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 105684607696896.0000 - mae: 7185413.5000 - val_loss: 77655374299136.0000 - val_mae: 6093746.5000
Epoch 4/100
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 71918380122112.0000 - mae: 5856264.0000 - val_loss: 64177968250880.0000 - val_mae: 5675884.5000
Epoch 5/100
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 21s 5ms/step - loss: 62128010559488.0000 - mae: 5581339.0000 - val_loss: 60639447875584.0000 - val_mae: 5565042.0000
Epoch 6/100
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 20s 5ms/step - loss: 58816410419200.0000 - mae: 5448259.5000 - val_loss: 57854664900608.0000 - val_mae: 5421534.0000
Epoch 7/100
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 21s 5ms/step - loss: 56012866322432.0000 - mae: 5300971.0000 - val_loss: 55401550708736.0000 - val_mae: 5288969.5000
Epoch 8/100
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 54063651618816.0000 - mae: 5180033.0000 - val_loss: 53181430104064.0000 - val_mae: 5156416.5000
Epoch 9/100
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 51832936202240.0000 - mae: 5057406.0000 - val_loss: 51117706706944.0000 - val_mae: 5024730.0000
Epoch 10/100

In [ ]:
# Step 13: Plot training & validation loss
plt.plot(history.history['loss'], label='train loss')
plt.plot(history.history['val_loss'], label='val loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()